userDB/userDB/urls.py
from django.contrib import admin
from django.urls import path, include
from userDB_app import views
from userDB import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from userDB_app import urls


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('userDB_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userDB/userDB_app/urls.py
from django.urls import path
from userDB_app import views


app_name = 'userDB_app'

urlpatterns = [
    path('user/', views.userView, name='user'),
    path('forms/', views.form_data, name='forms'),
    path('register/', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

userDB/userDB_app/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

# Create your models here.


class userDB(models.Model):
    first_name = models.CharField(max_length=50)

    last_name = models.CharField(max_length=50)

    username = models.CharField(unique=True, max_length=50)

    email = models.EmailField(unique=True)

    photo = models.ImageField(
        upload_to='gallery',
        default='gallery/img.jpeg',
        blank=True
    )

    def __str__(self):
        return "Name: " + self.first_name + " " + self.last_name + " ||| User Name: " + self.username + "    |||   Email: " + self.email


class UserProfileInfo(models.Model):

    # built-it

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )

    # additional

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(
        upload_to='profile_pics',
        blank=True
    )

    def __str__(self):
        return self.user.username

userDB/userDB_app/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from userDB_app.models import userDB
from . import form
from django.http import HttpResponsePermanentRedirect
from django.core.files.storage import FileSystemStorage
from userDB_app.form import User_login_form, User_profile_info_form, NewUserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def index(request):

    DB_form = NewUserForm()

    if request.method == 'POST':
        DB_form = NewUserForm(request.POST)

        if DB_form.is_valid():

            DB_form.save(commit=True)

            return userView(request)

        else:
            print('ERROR FORM INVALID')

    return render(
        request,
        'userDB_app/index.html',
        {
            'form': DB_form
        }
    )


user_d = userDB


def userView(request):

    user_data = user_d.objects.order_by('first_name')
    forms = form.FromUser()
    return render(
        request,
        'userDB_app/user.html',
        {
            'user_db': user_data
        }
    )


def form_data(request):
    forms = form.FromUser()
    if request.method == 'POST':
        forms = form.FromUser(request.POST)
        if forms.is_valid():
            print("SUCCESS!")
            print('First Name: ' + forms.cleaned_data['first_name'])
            print('Last Name: ' + forms.cleaned_data['last_name'])
            print('User Name: ' + forms.cleaned_data['user_name'])
            print('Last Name: ' + forms.cleaned_data['email'])

    return render(
        request,
        'userDB_app/forms.html',
        {
            'form': forms
        }
    )


def register(request):

    registered = False
    if request.method == 'POST':
        user_form = User_login_form(data=request.POST)
        profile_form = User_profile_info_form(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            # built-in
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # addition
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = User_login_form()
        profile_form = User_profile_info_form()

    return render(
        request,
        'userDB_app/register.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'registered': registered,
        }
    )


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(
            username=username,
            password=password
        )

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details!")

    else:
        return render(
            request,
            'userDB_app/login.html',
            {

            }
        )


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(
        reverse(
            'index'
        )
    )


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

userDB/templates/userDB_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}

        {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

   {% block head_css %}

    {% endblock %}
    
</head>

<body class="body">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'admin:index' %}">rsupanta DashBoard</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userDB_app:user' %}">User DB</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userDB_app:forms' %}">Form</a>
                </li>


                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userDB_app:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userDB_app:special' %}">Special</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userDB_app:user_login' %}">Login</a>
                </li>
                {% endif %}


            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>


    {% block body_block %}

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


</body>

</html>

userDB/templates/userDB_app/forms.html
{% extends 'userDB_app/base.html' %}

{% block title %}
Form
{% endblock %}

{% block body_block %}

<div class="jumbotron bg-secondary">
    <h1 class="text-center">Welcome!</h1>
    <h2 class="text-center">Add user to Database </h2>
    <br>


    <div class="card text-white bg-dark text-center container"
        style="max-width: 28rem;padding-top: 20px;padding-right: 20px;padding-left: 20px;">
        <div class="card-header">User Form</div>
        <div class="card-body">

            <div class="form-group">
                <form method="POST" class="">
                    <div class="form-group row">
                        {{form.first_name}}
                        <br><br>
                        {{form.last_name}}
                        <br><br>

                        {{form.user_name}}
                        <br><br>

                        {{form.email}}
                        <br><br>

                        {{form.verify_email}}
                        <br><br>
                        {{form.bio_text}}
                        <br><br>
                        {{form.bot_catcher}}

                        <div class="" style="width: 28rem;">
                            <br>
                            <input class=" btn btn-outline-success container" type="submit" value="Submit">
                        </div>



                        {% csrf_token %}

                </form>
            </div>
        </div>

    </div>


</div>


{% endblock %}

userDB/templates/userDB_app/index.html
{% extends 'userDB_app/base.html' %}

{% block title %}
Home
{% endblock %}

{% block head_css %}
<style>
    html {
        width: 100%;
        height: 100%;
        overflow: hidden;
    }
</style>
{% endblock %}

{% block body_block %}

<div class="jumbotron body text-white">
    <h1 class="text-center">Welcome!</h1>
    <br>
    <h2 class="text-center">Django Test Project </h2>
    
    <br>



    <div class="card text-white bg-dark text-center container card-shadow"
        style="max-width: 25rem;padding-top: 20px;padding-right: 20px;padding-left: 20px;">
        <div class="card-header lead">Add user to Database</div>
        <div class="card-body">
            <div class="form-group">
                <form enctype="multipart/form-data" method="POST">
                    <div class="form-group row">
                        {% csrf_token %}

                        {{ form.first_name }}
                        {{ form.last_name }}
                        {{ form.username }}
                        {{ form.email }}
                        {{ form.photo }}
                        {{ form.bot_catcher }}
                       
                        <input class="btn btn-outline-success container" style="max-width: 20rem;" type="submit" value="Submit">
                    

                </form>
            </div> 
        </div>

    </div>



</div>




{% endblock %}

userDB/templates/userDB_app/login.html
{% extends 'userDB_app/base.html' %}

{% block title %}
Login
{% endblock %}

{% block head_css %}
<style>
    html {
        width: 100%;
        height: 100%;
        overflow: hidden;
    }
</style>
{% endblock %}

{% block body_block %}


<div class="login">
    <h1 class="text-monospace">Login</h1>
    <form action="{% url 'userDB_app:user_login' %}" method="post">
        {% csrf_token %}
        <input class='input' type="text" name="username" placeholder="Username" required="required" />
        <input class='input' type="password" name="password" placeholder="Password" required="required" />
        <button type="submit" class="btnn btnn-primary btnn-block btnn-large">Let me in.</button>
        <br>
        <p class="text-monospace text-white">Don't have an account yet? <br>Don't worry. We've got your back!</p>
        <a class="btnn btnn-primary btnn-block btnn-large" href="{% url 'userDB_app:register' %}">Register here</a>
    </form>
</div>

{% endblock %}

userDB/templates/userDB_app/register.html
{% extends 'userDB_app/base.html' %}

{% block title %}
Register New User
{% endblock %}

{% block head_css %}
<style>
    html {
        width: 100%;
        height: 100%;
        overflow: hidden;
    }
</style>
{% endblock %}

{% block body_block %}

<!-- 
<div class="jumbotron bg-secondary jumbotron-fluid">
    <div class="container">
        {% if registered %}
        <h1>Thank you for registration!</h1>
        {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
        {% endif %}
    </div>
</div> -->

<div class="login text-white">
    {% if registered %}
    <h1>Thank you for registration!</h1>
    {% else %}
    <h1>Register Here</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.username }}
        {{ user_form.password }}
        {{ user_form.email }}
        {{ profile_form.portfolio_site }}
        {{ profile_form.profile_pic }}
        <button type="submit" class="btnn btnn-primary btnn-block btnn-large"
            style="padding-top: 10px; margin-top: 10px;">Let Me
            Register!</button>
    </form>
    {% endif %}
</div>



{% endblock %}

userDB/templates/userDB_app/user.html
{% extends 'userDB_app/base.html' %}

{% block title %}
User Database
{% endblock %}

{% block body_block %}

<div class="jumbotron bg-secondary text-white">
    <h1 class="text-center">Welcome!</h1>

    <br>
    <h2 class="text-center">User List from Database </h2>
    <br>
    <div class="container text-monospace">
        {% if user_db %}
        <table class="table container table-dark table-bordered table-hover table-responsive-sm table-striped">
            <thead class="thead-dark">
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">User Name</th>
                <th scope="col">Email</th>
            </thead>
            {% for acc in user_db %}
            <tr>
                <td scope="row">{{ acc.first_name }}</td>
                <td scope="row">{{ acc.last_name }}</td>
                <td scope="row">{{ acc.username|lower }}</td>
                <td scope="row">{{ acc.email }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No users found!</p>
        {% endif %}
    </div>



    <div class="container text-center">

        <div class="row">
            {% for user in user_db %}
            <div class="w-100 card text-white text-center shadow bg-secondary card-margin" style="max-width: 33rem;">
                <li class="text-white text-monospace lead bg-secondary card-margin">User info
                    of
                    {{ user.username }}:
                    <div class="text-center">
                        <img class="img-fluid" src="{{ user.photo.url }}">

                        <p class="">{{ user.username }}'s Photo</p>
                    </div>
                    <ol class="list-group-item disabled ">First Name: {{ user.first_name }}</ol>
                    <ol class="list-group-item disabled ">Last Name: {{ user.last_name }}</ol>
                    <ol class="list-group-item disabled ">User Name: {{ user.username|lower }}</ol>
                    <ol class="list-group-item disabled ">Email: {{ user.email }}</ol>
                </li>

            </div>
            {% endfor %}
        </div>

    </div>

</div>






{% endblock %}